xcode 15.0.1

diff --git a/.github/workflows/macos-13.yml b/.github/workflows/macos-13.yml
--- a/.github/workflows/macos-13.yml
+++ b/.github/workflows/macos-13.yml
@@ -16,7 +16,7 @@ jobs:
       fail-fast: true
       matrix:
         build:
-          - { os: macos-12, xcode: "14.2", deployment: 12.5 }
+          - { os: macos-13, xcode: "15.0", deployment: 13.5 }
         compiler:
           - { compiler: XCode,   CC: cc, CXX: c++ }
         btype: [ Release ]
@@ -41,45 +41,45 @@ jobs:
       - name: Applications folder
         run: |
           ls -l /Applications
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          submodules: true
-          path: src
-      - name: Install Base Dependencies
-        run: |
-          brew update > /dev/null || true
-          # brew upgrade || true        # No need for a very time-consuming upgrade of ALL packages
-          brew upgrade gd               # See https://github.com/Homebrew/homebrew-core/issues/141766
-          brew tap Homebrew/bundle
-          cd src/.ci
-          export HOMEBREW_NO_INSTALL_UPGRADE=1
-          brew bundle --verbose || true
-          # handle keg-only libs
-          brew link --force libomp
-          brew link --force libsoup@2
-      - name: use ImageMagick 6
-        run: |
-          brew link --overwrite --force imagemagick@6
-      - name: Cancel workflow if job fails
-        if: ${{ failure() }}
-        uses: andymckay/cancel-action@0.3
-      - name: Build and Install
-          # todo: use linker which supports --wrap, ld.bfd and ld.gold support it
-        run: |
-          cmake -E make_directory "${BUILD_DIR}";
-          cmake -E make_directory "${INSTALL_PREFIX}";
-          ./src/.ci/ci-script.sh;
-      - name: Check if it runs
-        run: |
-          ${INSTALL_PREFIX}/bin/darktable --version || true
-          ${INSTALL_PREFIX}/bin/darktable-cli \
-                 --width 2048 --height 2048 \
-                 --hq true --apply-custom-presets false \
-                 "${SRC_DIR}/src/tests/integration/images/mire1.cr2" \
-                 "${SRC_DIR}/src/tests/integration/0000-nop/nop.xmp" \
-                 output.png \
-                 --core --disable-opencl --conf host_memory_limit=8192 \
-                 --conf worker_threads=4 -t 4 \
-                 --conf plugins/lighttable/export/force_lcms2=FALSE \
-                 --conf plugins/lighttable/export/iccintent=0
+      # - uses: actions/checkout@v4
+      #   with:
+      #     fetch-depth: 0
+      #     submodules: true
+      #     path: src
+      # - name: Install Base Dependencies
+      #   run: |
+      #     brew update > /dev/null || true
+      #     # brew upgrade || true        # No need for a very time-consuming upgrade of ALL packages
+      #     brew upgrade gd               # See https://github.com/Homebrew/homebrew-core/issues/141766
+      #     brew tap Homebrew/bundle
+      #     cd src/.ci
+      #     export HOMEBREW_NO_INSTALL_UPGRADE=1
+      #     brew bundle --verbose || true
+      #     # handle keg-only libs
+      #     brew link --force libomp
+      #     brew link --force libsoup@2
+      # - name: use ImageMagick 6
+      #   run: |
+      #     brew link --overwrite --force imagemagick@6
+      # - name: Cancel workflow if job fails
+      #   if: ${{ failure() }}
+      #   uses: andymckay/cancel-action@0.3
+      # - name: Build and Install
+      #     # todo: use linker which supports --wrap, ld.bfd and ld.gold support it
+      #   run: |
+      #     cmake -E make_directory "${BUILD_DIR}";
+      #     cmake -E make_directory "${INSTALL_PREFIX}";
+      #     ./src/.ci/ci-script.sh;
+      # - name: Check if it runs
+      #   run: |
+      #     ${INSTALL_PREFIX}/bin/darktable --version || true
+      #     ${INSTALL_PREFIX}/bin/darktable-cli \
+      #            --width 2048 --height 2048 \
+      #            --hq true --apply-custom-presets false \
+      #            "${SRC_DIR}/src/tests/integration/images/mire1.cr2" \
+      #            "${SRC_DIR}/src/tests/integration/0000-nop/nop.xmp" \
+      #            output.png \
+      #            --core --disable-opencl --conf host_memory_limit=8192 \
+      #            --conf worker_threads=4 -t 4 \
+      #            --conf plugins/lighttable/export/force_lcms2=FALSE \
+      #            --conf plugins/lighttable/export/iccintent=0
